// The only place this data is defined is here. Change the ID's to whatever string or number you'd like, as well as every other option.
// This is a static file for now, but will eventually be built from an sqlite database

// TODO: Add real data. Only the first object in this array has real data. Everything else is randomly generated
people = [
    {
        name: "N. Steadman",
        imgpath: "img/faces/noel_steadman.jpg",
        id: "12-4",
        DOB: "26/12/1890",
        serviceID: "12/4",
        birthPlace: "Whangarei, New Zealand",
        DOD: "15/05/1915",
        occupation: "WW1 Electrical engineer",
        deathPlace: "Dardanelles, Gallipoli, Turkey.",
        deathcause: "Killed in Action",
        bio: "<p>N. Steadman was the son of Lieutenant-Colonel Thomas Herbert Steadman <i>(Territorial Force, 15th (North Auckland) Regiment)</i> and Edith Minnie Steadman of Whangarei. </p><p>He was a pupil at Whangarei High School during 1904 and 1905 but left in 1906 to enter King’s College in Auckland.</p><p>After leaving school he devoted his studies to engineering.</p><p>When war broke out he enlisted and left with the Main Body as a lieutenant in the Auckland Infantry. </p><p>He took part in the defence of the Suez Canal and the landing at Gallipoli and was afterwards killed on the 8th May 1915 in the attack on Krithia in the Dardanelles.</p>"
    },
    {
        name: "D. Schmidtke",
        imgpath: "img/faces/noel_steadman.jpg",
        id: "1",
        DOB: "09/10/1870",
        serviceID: "6/15",
        birthPlace: "Whangarei, New Zealand",
        DOD: "25/03/1915",
        occupation: "WW1 Electrical engineer",
        deathPlace: "Dardanelles, Gallipoli, Turkey.",
        deathcause: "Killed in Action",
        bio: "<p>D. Schmidtke was the son of Lieutenant-Colonel Thomas Herbert Steadman <i>(Territorial Force, 15th (North Auckland) Regiment)</i> and Edith Minnie Steadman of Whangarei. </p><p>He was a pupil at Whangarei High School during 1904 and 1905 but left in 1906 to enter King’s College in Auckland.</p><p>After leaving school he devoted his studies to engineering.</p><p>When war broke out he enlisted and left with the Main Body as a lieutenant in the Auckland Infantry. </p><p>He took part in the defence of the Suez Canal and the landing at Gallipoli and was afterwards killed on the 8th May 1915 in the attack on Krithia in the Dardanelles.</p>"
    },
    {
        name: "T. Lengyel",
        imgpath: "img/faces/noel_steadman.jpg",
        id: "2",
        DOB: "06/12/1870",
        serviceID: "10/11",
        birthPlace: "Whangarei, New Zealand",
        DOD: "10/06/1915",
        occupation: "WW1 Electrical engineer",
        deathPlace: "Dardanelles, Gallipoli, Turkey.",
        deathcause: "Killed in Action",
        bio: "<p>T. Lengyel was the son of Lieutenant-Colonel Thomas Herbert Steadman <i>(Territorial Force, 15th (North Auckland) Regiment)</i> and Edith Minnie Steadman of Whangarei. </p><p>He was a pupil at Whangarei High School during 1904 and 1905 but left in 1906 to enter King’s College in Auckland.</p><p>After leaving school he devoted his studies to engineering.</p><p>When war broke out he enlisted and left with the Main Body as a lieutenant in the Auckland Infantry. </p><p>He took part in the defence of the Suez Canal and the landing at Gallipoli and was afterwards killed on the 8th May 1915 in the attack on Krithia in the Dardanelles.</p>"
    },
    {
        name: "U. Dejarnette",
        imgpath: "img/faces/noel_steadman.jpg",
        id: "3",
        DOB: "05/12/1873",
        serviceID: "2/4",
        birthPlace: "Whangarei, New Zealand",
        DOD: "08/12/1915",
        occupation: "WW1 Electrical engineer",
        deathPlace: "Dardanelles, Gallipoli, Turkey.",
        deathcause: "Killed in Action",
        bio: "<p>U. Dejarnette was the son of Lieutenant-Colonel Thomas Herbert Steadman <i>(Territorial Force, 15th (North Auckland) Regiment)</i> and Edith Minnie Steadman of Whangarei. </p><p>He was a pupil at Whangarei High School during 1904 and 1905 but left in 1906 to enter King’s College in Auckland.</p><p>After leaving school he devoted his studies to engineering.</p><p>When war broke out he enlisted and left with the Main Body as a lieutenant in the Auckland Infantry. </p><p>He took part in the defence of the Suez Canal and the landing at Gallipoli and was afterwards killed on the 8th May 1915 in the attack on Krithia in the Dardanelles.</p>"
    },
    {
        name: "C. Lacross",
        imgpath: "img/faces/noel_steadman.jpg",
        id: "4",
        DOB: "25/05/1875",
        serviceID: "6/4",
        birthPlace: "Whangarei, New Zealand",
        DOD: "09/01/1916",
        occupation: "WW1 Electrical engineer",
        deathPlace: "Dardanelles, Gallipoli, Turkey.",
        deathcause: "Killed in Action",
        bio: "<p>C. Lacross was the son of Lieutenant-Colonel Thomas Herbert Steadman <i>(Territorial Force, 15th (North Auckland) Regiment)</i> and Edith Minnie Steadman of Whangarei. </p><p>He was a pupil at Whangarei High School during 1904 and 1905 but left in 1906 to enter King’s College in Auckland.</p><p>After leaving school he devoted his studies to engineering.</p><p>When war broke out he enlisted and left with the Main Body as a lieutenant in the Auckland Infantry. </p><p>He took part in the defence of the Suez Canal and the landing at Gallipoli and was afterwards killed on the 8th May 1915 in the attack on Krithia in the Dardanelles.</p>"
    },
    {
        name: "A. Abram",
        imgpath: "img/faces/noel_steadman.jpg",
        id: "5",
        DOB: "30/04/1877",
        serviceID: "12/13",
        birthPlace: "Whangarei, New Zealand",
        DOD: "11/02/1916",
        occupation: "WW1 Electrical engineer",
        deathPlace: "Dardanelles, Gallipoli, Turkey.",
        deathcause: "Killed in Action",
        bio: "<p>A. Abram was the son of Lieutenant-Colonel Thomas Herbert Steadman <i>(Territorial Force, 15th (North Auckland) Regiment)</i> and Edith Minnie Steadman of Whangarei. </p><p>He was a pupil at Whangarei High School during 1904 and 1905 but left in 1906 to enter King’s College in Auckland.</p><p>After leaving school he devoted his studies to engineering.</p><p>When war broke out he enlisted and left with the Main Body as a lieutenant in the Auckland Infantry. </p><p>He took part in the defence of the Suez Canal and the landing at Gallipoli and was afterwards killed on the 8th May 1915 in the attack on Krithia in the Dardanelles.</p>"
    },
    {
        name: "R. Doepke",
        imgpath: "img/faces/noel_steadman.jpg",
        id: "6",
        DOB: "02/02/1878",
        serviceID: "12/7",
        birthPlace: "Whangarei, New Zealand",
        DOD: "02/04/1916",
        occupation: "WW1 Electrical engineer",
        deathPlace: "Dardanelles, Gallipoli, Turkey.",
        deathcause: "Killed in Action",
        bio: "<p>R. Doepke was the son of Lieutenant-Colonel Thomas Herbert Steadman <i>(Territorial Force, 15th (North Auckland) Regiment)</i> and Edith Minnie Steadman of Whangarei. </p><p>He was a pupil at Whangarei High School during 1904 and 1905 but left in 1906 to enter King’s College in Auckland.</p><p>After leaving school he devoted his studies to engineering.</p><p>When war broke out he enlisted and left with the Main Body as a lieutenant in the Auckland Infantry. </p><p>He took part in the defence of the Suez Canal and the landing at Gallipoli and was afterwards killed on the 8th May 1915 in the attack on Krithia in the Dardanelles.</p>"
    },
    {
        name: "M. Lummus",
        imgpath: "img/faces/noel_steadman.jpg",
        id: "7",
        DOB: "23/08/1879",
        serviceID: "8/14",
        birthPlace: "Whangarei, New Zealand",
        DOD: "14/05/1916",
        occupation: "WW1 Electrical engineer",
        deathPlace: "Dardanelles, Gallipoli, Turkey.",
        deathcause: "Killed in Action",
        bio: "<p>M. Lummus was the son of Lieutenant-Colonel Thomas Herbert Steadman <i>(Territorial Force, 15th (North Auckland) Regiment)</i> and Edith Minnie Steadman of Whangarei. </p><p>He was a pupil at Whangarei High School during 1904 and 1905 but left in 1906 to enter King’s College in Auckland.</p><p>After leaving school he devoted his studies to engineering.</p><p>When war broke out he enlisted and left with the Main Body as a lieutenant in the Auckland Infantry. </p><p>He took part in the defence of the Suez Canal and the landing at Gallipoli and was afterwards killed on the 8th May 1915 in the attack on Krithia in the Dardanelles.</p>"
    },
    {
        name: "R. Salvador",
        imgpath: "img/faces/noel_steadman.jpg",
        id: "8",
        DOB: "09/09/1879",
        serviceID: "8/15",
        birthPlace: "Whangarei, New Zealand",
        DOD: "03/06/1916",
        occupation: "WW1 Electrical engineer",
        deathPlace: "Dardanelles, Gallipoli, Turkey.",
        deathcause: "Killed in Action",
        bio: "<p>R. Salvador was the son of Lieutenant-Colonel Thomas Herbert Steadman <i>(Territorial Force, 15th (North Auckland) Regiment)</i> and Edith Minnie Steadman of Whangarei. </p><p>He was a pupil at Whangarei High School during 1904 and 1905 but left in 1906 to enter King’s College in Auckland.</p><p>After leaving school he devoted his studies to engineering.</p><p>When war broke out he enlisted and left with the Main Body as a lieutenant in the Auckland Infantry. </p><p>He took part in the defence of the Suez Canal and the landing at Gallipoli and was afterwards killed on the 8th May 1915 in the attack on Krithia in the Dardanelles.</p>"
    },
    {
        name: "A. Sharpton",
        imgpath: "img/faces/noel_steadman.jpg",
        id: "9",
        DOB: "09/10/1880",
        serviceID: "19/8",
        birthPlace: "Whangarei, New Zealand",
        DOD: "17/06/1916",
        occupation: "WW1 Electrical engineer",
        deathPlace: "Dardanelles, Gallipoli, Turkey.",
        deathcause: "Killed in Action",
        bio: "<p>A. Sharpton was the son of Lieutenant-Colonel Thomas Herbert Steadman <i>(Territorial Force, 15th (North Auckland) Regiment)</i> and Edith Minnie Steadman of Whangarei. </p><p>He was a pupil at Whangarei High School during 1904 and 1905 but left in 1906 to enter King’s College in Auckland.</p><p>After leaving school he devoted his studies to engineering.</p><p>When war broke out he enlisted and left with the Main Body as a lieutenant in the Auckland Infantry. </p><p>He took part in the defence of the Suez Canal and the landing at Gallipoli and was afterwards killed on the 8th May 1915 in the attack on Krithia in the Dardanelles.</p>"
    },
    {
        name: "C. Watford",
        imgpath: "img/faces/noel_steadman.jpg",
        id: "10",
        DOB: "20/02/1881",
        serviceID: "12/20",
        birthPlace: "Whangarei, New Zealand",
        DOD: "15/07/1916",
        occupation: "WW1 Electrical engineer",
        deathPlace: "Dardanelles, Gallipoli, Turkey.",
        deathcause: "Killed in Action",
        bio: "<p>C. Watford was the son of Lieutenant-Colonel Thomas Herbert Steadman <i>(Territorial Force, 15th (North Auckland) Regiment)</i> and Edith Minnie Steadman of Whangarei. </p><p>He was a pupil at Whangarei High School during 1904 and 1905 but left in 1906 to enter King’s College in Auckland.</p><p>After leaving school he devoted his studies to engineering.</p><p>When war broke out he enlisted and left with the Main Body as a lieutenant in the Auckland Infantry. </p><p>He took part in the defence of the Suez Canal and the landing at Gallipoli and was afterwards killed on the 8th May 1915 in the attack on Krithia in the Dardanelles.</p>"
    },
    {
        name: "D. Kahan",
        imgpath: "img/faces/noel_steadman.jpg",
        id: "11",
        DOB: "10/05/1881",
        serviceID: "10/5",
        birthPlace: "Whangarei, New Zealand",
        DOD: "08/10/1916",
        occupation: "WW1 Electrical engineer",
        deathPlace: "Dardanelles, Gallipoli, Turkey.",
        deathcause: "Killed in Action",
        bio: "<p>D. Kahan was the son of Lieutenant-Colonel Thomas Herbert Steadman <i>(Territorial Force, 15th (North Auckland) Regiment)</i> and Edith Minnie Steadman of Whangarei. </p><p>He was a pupil at Whangarei High School during 1904 and 1905 but left in 1906 to enter King’s College in Auckland.</p><p>After leaving school he devoted his studies to engineering.</p><p>When war broke out he enlisted and left with the Main Body as a lieutenant in the Auckland Infantry. </p><p>He took part in the defence of the Suez Canal and the landing at Gallipoli and was afterwards killed on the 8th May 1915 in the attack on Krithia in the Dardanelles.</p>"
    },
    {
        name: "A. Stjean",
        imgpath: "img/faces/noel_steadman.jpg",
        id: "12",
        DOB: "03/02/1882",
        serviceID: "16/15",
        birthPlace: "Whangarei, New Zealand",
        DOD: "17/01/1917",
        occupation: "WW1 Electrical engineer",
        deathPlace: "Dardanelles, Gallipoli, Turkey.",
        deathcause: "Killed in Action",
        bio: "<p>A. Stjean was the son of Lieutenant-Colonel Thomas Herbert Steadman <i>(Territorial Force, 15th (North Auckland) Regiment)</i> and Edith Minnie Steadman of Whangarei. </p><p>He was a pupil at Whangarei High School during 1904 and 1905 but left in 1906 to enter King’s College in Auckland.</p><p>After leaving school he devoted his studies to engineering.</p><p>When war broke out he enlisted and left with the Main Body as a lieutenant in the Auckland Infantry. </p><p>He took part in the defence of the Suez Canal and the landing at Gallipoli and was afterwards killed on the 8th May 1915 in the attack on Krithia in the Dardanelles.</p>"
    },
    {
        name: "G. Parisien",
        imgpath: "img/faces/noel_steadman.jpg",
        id: "13",
        DOB: "25/06/1883",
        serviceID: "16/13",
        birthPlace: "Whangarei, New Zealand",
        DOD: "31/07/1917",
        occupation: "WW1 Electrical engineer",
        deathPlace: "Dardanelles, Gallipoli, Turkey.",
        deathcause: "Killed in Action",
        bio: "<p>G. Parisien was the son of Lieutenant-Colonel Thomas Herbert Steadman <i>(Territorial Force, 15th (North Auckland) Regiment)</i> and Edith Minnie Steadman of Whangarei. </p><p>He was a pupil at Whangarei High School during 1904 and 1905 but left in 1906 to enter King’s College in Auckland.</p><p>After leaving school he devoted his studies to engineering.</p><p>When war broke out he enlisted and left with the Main Body as a lieutenant in the Auckland Infantry. </p><p>He took part in the defence of the Suez Canal and the landing at Gallipoli and was afterwards killed on the 8th May 1915 in the attack on Krithia in the Dardanelles.</p>"
    },
    {
        name: "N. Kost",
        imgpath: "img/faces/noel_steadman.jpg",
        id: "14",
        DOB: "03/08/1883",
        serviceID: "2/3",
        birthPlace: "Whangarei, New Zealand",
        DOD: "18/10/1917",
        occupation: "WW1 Electrical engineer",
        deathPlace: "Dardanelles, Gallipoli, Turkey.",
        deathcause: "Killed in Action",
        bio: "<p>N. Kost was the son of Lieutenant-Colonel Thomas Herbert Steadman <i>(Territorial Force, 15th (North Auckland) Regiment)</i> and Edith Minnie Steadman of Whangarei. </p><p>He was a pupil at Whangarei High School during 1904 and 1905 but left in 1906 to enter King’s College in Auckland.</p><p>After leaving school he devoted his studies to engineering.</p><p>When war broke out he enlisted and left with the Main Body as a lieutenant in the Auckland Infantry. </p><p>He took part in the defence of the Suez Canal and the landing at Gallipoli and was afterwards killed on the 8th May 1915 in the attack on Krithia in the Dardanelles.</p>"
    },
    {
        name: "C. Winslow",
        imgpath: "img/faces/noel_steadman.jpg",
        id: "15",
        DOB: "16/01/1885",
        serviceID: "11/17",
        birthPlace: "Whangarei, New Zealand",
        DOD: "04/11/1917",
        occupation: "WW1 Electrical engineer",
        deathPlace: "Dardanelles, Gallipoli, Turkey.",
        deathcause: "Killed in Action",
        bio: "<p>C. Winslow was the son of Lieutenant-Colonel Thomas Herbert Steadman <i>(Territorial Force, 15th (North Auckland) Regiment)</i> and Edith Minnie Steadman of Whangarei. </p><p>He was a pupil at Whangarei High School during 1904 and 1905 but left in 1906 to enter King’s College in Auckland.</p><p>After leaving school he devoted his studies to engineering.</p><p>When war broke out he enlisted and left with the Main Body as a lieutenant in the Auckland Infantry. </p><p>He took part in the defence of the Suez Canal and the landing at Gallipoli and was afterwards killed on the 8th May 1915 in the attack on Krithia in the Dardanelles.</p>"
    },
    {
        name: "G. Dubin",
        imgpath: "img/faces/noel_steadman.jpg",
        id: "16",
        DOB: "16/11/1885",
        serviceID: "5/4",
        birthPlace: "Whangarei, New Zealand",
        DOD: "01/03/1918",
        occupation: "WW1 Electrical engineer",
        deathPlace: "Dardanelles, Gallipoli, Turkey.",
        deathcause: "Killed in Action",
        bio: "<p>G. Dubin was the son of Lieutenant-Colonel Thomas Herbert Steadman <i>(Territorial Force, 15th (North Auckland) Regiment)</i> and Edith Minnie Steadman of Whangarei. </p><p>He was a pupil at Whangarei High School during 1904 and 1905 but left in 1906 to enter King’s College in Auckland.</p><p>After leaving school he devoted his studies to engineering.</p><p>When war broke out he enlisted and left with the Main Body as a lieutenant in the Auckland Infantry. </p><p>He took part in the defence of the Suez Canal and the landing at Gallipoli and was afterwards killed on the 8th May 1915 in the attack on Krithia in the Dardanelles.</p>"
    },
    {
        name: "E. Andersen",
        imgpath: "img/faces/noel_steadman.jpg",
        id: "17",
        DOB: "17/09/1887",
        serviceID: "8/19",
        birthPlace: "Whangarei, New Zealand",
        DOD: "29/04/1918",
        occupation: "WW1 Electrical engineer",
        deathPlace: "Dardanelles, Gallipoli, Turkey.",
        deathcause: "Killed in Action",
        bio: "<p>E. Andersen was the son of Lieutenant-Colonel Thomas Herbert Steadman <i>(Territorial Force, 15th (North Auckland) Regiment)</i> and Edith Minnie Steadman of Whangarei. </p><p>He was a pupil at Whangarei High School during 1904 and 1905 but left in 1906 to enter King’s College in Auckland.</p><p>After leaving school he devoted his studies to engineering.</p><p>When war broke out he enlisted and left with the Main Body as a lieutenant in the Auckland Infantry. </p><p>He took part in the defence of the Suez Canal and the landing at Gallipoli and was afterwards killed on the 8th May 1915 in the attack on Krithia in the Dardanelles.</p>"
    },
    {
        name: "J. Conkling",
        imgpath: "img/faces/noel_steadman.jpg",
        id: "18",
        DOB: "24/04/1888",
        serviceID: "3/17",
        birthPlace: "Whangarei, New Zealand",
        DOD: "12/05/1918",
        occupation: "WW1 Electrical engineer",
        deathPlace: "Dardanelles, Gallipoli, Turkey.",
        deathcause: "Killed in Action",
        bio: "<p>J. Conkling was the son of Lieutenant-Colonel Thomas Herbert Steadman <i>(Territorial Force, 15th (North Auckland) Regiment)</i> and Edith Minnie Steadman of Whangarei. </p><p>He was a pupil at Whangarei High School during 1904 and 1905 but left in 1906 to enter King’s College in Auckland.</p><p>After leaving school he devoted his studies to engineering.</p><p>When war broke out he enlisted and left with the Main Body as a lieutenant in the Auckland Infantry. </p><p>He took part in the defence of the Suez Canal and the landing at Gallipoli and was afterwards killed on the 8th May 1915 in the attack on Krithia in the Dardanelles.</p>"
    },
    {
        name: "L. Fredericks",
        imgpath: "img/faces/noel_steadman.jpg",
        id: "19",
        DOB: "02/02/1889",
        serviceID: "9/8",
        birthPlace: "Whangarei, New Zealand",
        DOD: "05/08/1918",
        occupation: "WW1 Electrical engineer",
        deathPlace: "Dardanelles, Gallipoli, Turkey.",
        deathcause: "Killed in Action",
        bio: "<p>L. Fredericks was the son of Lieutenant-Colonel Thomas Herbert Steadman <i>(Territorial Force, 15th (North Auckland) Regiment)</i> and Edith Minnie Steadman of Whangarei. </p><p>He was a pupil at Whangarei High School during 1904 and 1905 but left in 1906 to enter King’s College in Auckland.</p><p>After leaving school he devoted his studies to engineering.</p><p>When war broke out he enlisted and left with the Main Body as a lieutenant in the Auckland Infantry. </p><p>He took part in the defence of the Suez Canal and the landing at Gallipoli and was afterwards killed on the 8th May 1915 in the attack on Krithia in the Dardanelles.</p>"
    },
    {
        name: "L. Harris",
        imgpath: "img/faces/noel_steadman.jpg",
        id: "20",
        DOB: "05/04/1889",
        serviceID: "10/17",
        birthPlace: "Whangarei, New Zealand",
        DOD: "18/09/1918",
        occupation: "WW1 Electrical engineer",
        deathPlace: "Dardanelles, Gallipoli, Turkey.",
        deathcause: "Killed in Action",
        bio: "<p>L. Harris was the son of Lieutenant-Colonel Thomas Herbert Steadman <i>(Territorial Force, 15th (North Auckland) Regiment)</i> and Edith Minnie Steadman of Whangarei. </p><p>He was a pupil at Whangarei High School during 1904 and 1905 but left in 1906 to enter King’s College in Auckland.</p><p>After leaving school he devoted his studies to engineering.</p><p>When war broke out he enlisted and left with the Main Body as a lieutenant in the Auckland Infantry. </p><p>He took part in the defence of the Suez Canal and the landing at Gallipoli and was afterwards killed on the 8th May 1915 in the attack on Krithia in the Dardanelles.</p>"
    }
];