// The only place this data is defined is here. Change the ID's to whatever string or number you'd like, as well as every other option.
// This is a static file for now, but will eventually be built from an sqlite database
// TODO: Add real data. Only the first object in this array has real data. Everything else is randomly generated
people = [{
        name: "N. Steadman",
        imgpath: "img/faces/noel_steadman.jpg",
        id: "12-4",
        DOB: "26/12/1890",
        serviceID: "12/4",
        birthPlace: "Whangarei, New Zealand",
        DOD: "15/05/1915",
        occupation: "WW1 Electrical engineer",
        deathPlace: "Dardanelles, Gallipoli, Turkey.",
        deathcause: "Killed in Action",
        bio: "<p>N. Steadman was the son of Lieutenant-Colonel Thomas Herbert Steadman <i>(Territorial Force, 15th (North Auckland) Regiment)</i> and Edith Minnie Steadman of Whangarei. </p><p>He was a pupil at Whangarei High School during 1904 and 1905 but left in 1906 to enter King’s College in Auckland.</p><p>After leaving school he devoted his studies to engineering.</p><p>When war broke out he enlisted and left with the Main Body as a lieutenant in the Auckland Infantry. </p><p>He took part in the defence of the Suez Canal and the landing at Gallipoli and was afterwards killed on the 8th May 1915 in the attack on Krithia in the Dardanelles.</p>"
    }, {
        name: "F.C. Baker",
        fullname: "Francis Charles Baker",
        imgpath: "img/faces/ID.jpg",
        id: "44246",
        DOB: " ",
        serviceID: "44246",
        birthPlace: " ",
        DOD: "8 December 1917",
        occupation: "WW1 Telegraph cadet clerk",
        deathPlace: "Ypres, Belgium",
        deathcause: "Killed in Action",
        bio: "Francis Charles Baker, a son of Mr C. H. Baker, of Whangarei, received his primary education at Hora Hora and attended Whangarei High School during 1911. Notwithstanding his short period at the High School he took a prominent part in the activities of the first-year people and was a general favourite among his school-follows. In 1912 he took a position in the Post Office in Whangarei. He joined up with the 24ths, and saw service for a short time in France where he was killed while on duty in the front line trenches."
    }, {
        name: "F.L. Beasley",
        fullname: " ",
        imgpath: "img/faces/ID.jpg",
        id: " ",
        DOB: " ",
        serviceID: " ",
        birthPlace: " ",
        DOD: " ",
        occupation: " ",
        deathPlace: " ",
        deathcause: " ",
        bio: " "
    }, {
        name: "R.P. Bedlington",
        fullname: " ROY P. BEDLINGTON.",
        imgpath: "img/faces/ID.jpg",
        id: "4-1146",
        DOB: " ",
        serviceID: "4/1146 & 12/1146",
        birthPlace: " ",
        DOD: "30 November 1915",
        occupation: " ",
        deathPlace: "Gallipoli, Turkey",
        deathcause: "Killed in Action",
        bio: "Roy P. Bedlington, elder son of the late Mr. Percy Bedlington, of Whangarei, attended the High School during 1909 and 1910. On leaving school he went to the Whangarei Engineering Company and remained there until his enlistment at the beginning of the war. He left with the 2nd Reinforcements with the N.Z. Engineers as a sapper and took part in the landing on Gallipoli. He was killed on November 30th, 1919. Roy's quiet, good humour and his gift for droll speech marked him as a general favourite at school. Whether at school, or in the works, or on duty Roy was the same good comrade. He lies on Gallipoli, one of the heroes who made New Zealand’s name famous throughout the world."
    }, {
        name: "B.B. Bindon",
        fullname: " ",
        imgpath: "img/faces/ID.jpg",
        id: " ",
        DOB: " ",
        serviceID: " ",
        birthPlace: " ",
        DOD: " ",
        occupation: " ",
        deathPlace: " ",
        deathcause: " ",
        bio: " "
    }, {
        name: "A.N. Brown",
        fullname: " ",
        imgpath: "img/faces/ID.jpg",
        id: " ",
        DOB: " ",
        serviceID: " ",
        birthPlace: " ",
        DOD: " ",
        occupation: " ",
        deathPlace: " ",
        deathcause: " ",
        bio: " "
    }, {
        name: "H.J. Cameron",
        fullname: " ",
        imgpath: "img/faces/ID.jpg",
        id: " ",
        DOB: " ",
        serviceID: " ",
        birthPlace: " ",
        DOD: " ",
        occupation: " ",
        deathPlace: " ",
        deathcause: " ",
        bio: " "
    }, {
        name: "T. Cameron",
        fullname: "Tui Crawford Cameron",
        imgpath: "img/faces/ID.jpg",
        id: " ",
        DOB: " ",
        serviceID: " ",
        birthPlace: " ",
        DOD: " ",
        occupation: " ",
        deathPlace: " ",
        deathcause: " ",
        bio: "Tui Crawford Cameron, the youngest son of Mr Thos. Cameron, of Hora Hora, Whangarei, was with us for over three years. He enrolled in February, 1909, and left in 1912. After leaving school he entered business and en listed at the earliest opportunity. With Frank McKenzie, he joined the 13ths and saw service in France. He was present during the successful opening of the battle of the Somme in 1916 and after a very successful forward push was killed in the holding trenches.Tuj was ever to the front in whatever was going on. He was a very popular junior. His amiable disposition and genial good-humour made him a centre of attraction among the members of the junior forms."
    }, {
        name: "R. Carter",
        fullname: " ",
        imgpath: "img/faces/ID.jpg",
        id: " ",
        DOB: " ",
        serviceID: " ",
        birthPlace: " ",
        DOD: " ",
        occupation: " ",
        deathPlace: " ",
        deathcause: " ",
        bio: " "
    }, {
        name: "C.O.A. Cowan ",
        fullname: " ",
        imgpath: "img/faces/ID.jpg",
        id: " ",
        DOB: " ",
        serviceID: " ",
        birthPlace: " ",
        DOD: " ",
        occupation: " ",
        deathPlace: " ",
        deathcause: " ",
        bio: " "
    }, {
        name: "W.L. Clapson",
        fullname: " ",
        imgpath: "img/faces/ID.jpg",
        id: " ",
        DOB: " ",
        serviceID: " ",
        birthPlace: " ",
        DOD: " ",
        occupation: " ",
        deathPlace: " ",
        deathcause: " ",
        bio: " "
    }, {
        name: "B.C. Drake",
        fullname: " ",
        imgpath: "img/faces/ID.jpg",
        id: " ",
        DOB: " ",
        serviceID: " ",
        birthPlace: " ",
        DOD: " ",
        occupation: " ",
        deathPlace: " ",
        deathcause: " ",
        bio: " "
    }, {
        name: "J.C. Galbraith",
        fullname: " ",
        imgpath: "img/faces/ID.jpg",
        id: " ",
        DOB: " ",
        serviceID: " ",
        birthPlace: " ",
        DOD: " ",
        occupation: " ",
        deathPlace: " ",
        deathcause: " ",
        bio: " "
    }, {
        name: "C.H. Goodson",
        fullname: " ",
        imgpath: "img/faces/ID.jpg",
        id: " ",
        DOB: " ",
        serviceID: " ",
        birthPlace: " ",
        DOD: " ",
        occupation: " ",
        deathPlace: " ",
        deathcause: " ",
        bio: " "
    }, {
        name: "C.E. Gribble",
        fullname: " ",
        imgpath: "img/faces/ID.jpg",
        id: " ",
        DOB: " ",
        serviceID: " ",
        birthPlace: " ",
        DOD: " ",
        occupation: " ",
        deathPlace: " ",
        deathcause: " ",
        bio: " "
    }, {
        name: "H.F. Griffin",
        fullname: " ",
        imgpath: "img/faces/ID.jpg",
        id: " ",
        DOB: " ",
        serviceID: " ",
        birthPlace: " ",
        DOD: " ",
        occupation: " ",
        deathPlace: " ",
        deathcause: " ",
        bio: " "
    }, {
        name: "C.H. Hill",
        fullname: " ",
        imgpath: "img/faces/ID.jpg",
        id: " ",
        DOB: " ",
        serviceID: " ",
        birthPlace: " ",
        DOD: " ",
        occupation: " ",
        deathPlace: " ",
        deathcause: " ",
        bio: " "
    }, {
        name: "A.D. Jack",
        fullname: " ",
        imgpath: "img/faces/ID.jpg",
        id: " ",
        DOB: " ",
        serviceID: " ",
        birthPlace: " ",
        DOD: " ",
        occupation: " ",
        deathPlace: " ",
        deathcause: " ",
        bio: " "
    }, {
        name: "D.L. Jack ",
        fullname: "Donald Leslie Jack",
        imgpath: "img/faces/ID.jpg",
        id: " ",
        DOB: " ",
        serviceID: " ",
        birthPlace: " ",
        DOD: " ",
        occupation: " ",
        deathPlace: " ",
        deathcause: " ",
        bio: "Donald Leslie Jack was born in 1891 and was the third son of Mr Donald Jack, a former Mayor of Whangarei and always a prominent citizen. Les. was at High School for two years, 1907 and 1908, and after qualifying at the Public Service Examination he left to learn farming. Later he entered the teaching profession and joined the Training College the year before the outbreak of war. He volunteered for service with the Samoan Expeditionary Force and after the peaceful occupation of the islands, he returned to New Zealand. While recruiting his health at Whangarei he volunteered for service in France, joined the Rifle Brigade and left New Zealand as a corporal in the First Battalion of the N.Z.R.B. He was killed during the first battle of the Somme on 15th September, 1916. Les. Jack, following the example of his brother Will, took a prominent part in all school activities and speedily made his mark at football, earning his place in the school fifteen by sheer grit. He was a popular boy, his unfailing and buoyant spirits endeared him to all. He did creditable work in the classroom, was indefatigable in the pursuit of out-door recreations, and was loved by all who came in contact with him for his unfailing cheerfulness and solid work."
    }, {
        name: "O.P. Johnston",
        fullname: "OLAF JOHNSON",
        imgpath: "img/faces/ID.jpg",
        id: " ",
        DOB: " ",
        serviceID: " ",
        birthPlace: " ",
        DOD: " ",
        occupation: " ",
        deathPlace: " ",
        deathcause: " ",
        bio: "Olaf Johnson, son of Mr J. C. Johnson, late well-known settler of the Whananaki district, was at the High School for three years, 1905-7. He matriculated and then returned home to assist on his father's farm. He left with the A.M.R. in the 2nd Reinforcement as a lieutenant. Later, on Gallipoli, he was promoted to captain. He was killed in action on August 9th, 1916. Olaf was known in school as a boxer of some repute, end a successful student. Of a frank and cheery disposition he became prominent in all school activities and could be relied upon to ''stick it out'' to the last. Absolutely without fear his actions sometimes seemed to be foolhardy and it was perhaps this fearlessness which caused him to lose his life. We shall mourn Olaf as a gentleman, keen soldier, and one who took a sincere interest in the welfare of his old school. Like Harry Cameron he, too, made a special trip to see us all just before embarking."
    }, {
        name: "M.A. McDonald",
        fullname: " ",
        imgpath: "img/faces/ID.jpg",
        id: " ",
        DOB: " ",
        serviceID: " ",
        birthPlace: " ",
        DOD: " ",
        occupation: " ",
        deathPlace: " ",
        deathcause: " ",
        bio: " "
    }, {
        name: "F.J. McKenzie",
        fullname: "Frank J. McKenzie",
        imgpath: "img/faces/ID.jpg",
        id: " ",
        DOB: " ",
        serviceID: " ",
        birthPlace: " ",
        DOD: " ",
        occupation: " ",
        deathPlace: " ",
        deathcause: " ",
        bio: "Frank J. McKenzie was born at the Whangarei heads and entered school late, more than a year after he qualified for his junior free place. Although he only stayed with us for two years he quickly won his way into the school fifteen by sheer pluck and dash, and into the hearts of his school mates by his genial manners and sterling qualities. Leaving school h? entered the service of the Education Board, Auckland; was at the Training College in 1915, and enlisted in the 13th Reinforcements. When on final leave Frank took the opportunity of revisiting his ?ld school and came on the same day that six or seven old boys, who had joined the 12ths, were calling to say good-bye. Frank was proud of being in the Devil's Own, as the 13ths were known in camp and took in great good humour the banter he received owing to the recent raid on the canteen in camp—something put down to the lively manners  of the boys of the 13th Reinforcement. Frank would carry on in the battlefield as a cheery, bravo-hearted  boy would do, a favourite with all. He was wounded severely in a voluntary raid at Armentieres and died of wounds on March 1st in Boulogne."
    }, {
        name: "R.W. McKenzie",
        fullname: " ",
        imgpath: "img/faces/ID.jpg",
        id: " ",
        DOB: " ",
        serviceID: " ",
        birthPlace: " ",
        DOD: " ",
        occupation: " ",
        deathPlace: " ",
        deathcause: " ",
        bio: " "
    }, {
        name: "A. McLeod",
        fullname: "ALEXANDER McLEOD",
        imgpath: "img/faces/ID.jpg",
        id: " ",
        DOB: " ",
        serviceID: " ",
        birthPlace: " ",
        DOD: " ",
        occupation: " ",
        deathPlace: " ",
        deathcause: " ",
        bio: "Alexander McLeod, or Axie as he was universally called, was a son of Mr D. M. McLeod, of Whau Valley, Whangarei. Alex. was at the High school during 1906. After leaving school he was farming with his father. When war broke out he enlisted and left with the Main Body as a trooper in the Auckland Mounted Rifles. He landed at Gallipoli and was among those reported missing on 8th August,1915. Axie. became a popular boy on the first day of his High School life. Almost new to football he quickly picked up a knowledge of the game as a hard-working forward. Absolutely fearless, he could always be relied upon to stop an ugly rush and although his second career was a short one it was still long enough to make him popular member of school. We were indeed sorry that he was unable to be with us for more than one year."
    }, {
        name: "J.D. McLeod",
        fullname: "Johndy MacLeod",
        imgpath: "img/faces/ID.jpg",
        id: " ",
        DOB: " ",
        serviceID: " ",
        birthPlace: " ",
        DOD: " ",
        occupation: " ",
        deathPlace: " ",
        deathcause: " ",
        bio: "J. D. MacLeod, ''Johndy'' as he was familiarly known, was a son of the late Mr. Donald MacLeod, a well-known Hikurangi settler. He entered the High School in 1905, matriculated in 1908, and took his Senior Civil Service exam. in 1909. Entering the teaching profession he pa?sed through the Training College and went to KeriKeri, Bay of Islands, and later on to Tangowahine. He joined the 8th Reinforcements and was posted as sergeant in a Canterbury Infantry Battalion.He was among those killed in the first battle of the Somme in September, 1916. Although quiet and unassuming, J. D. MacLeod thoroughly enjoyed his school life, scoring success possibly more as a student than as an athlete. As a senior in the school his influence among his school fellows was decidedly good. ''Johandy'' was thoroughly popular wherever he went. His death in France has cut short a life of quiet inspiration and fine influence among the people he lived and worked among."
    }, {
        name: "C.J. Marshall",
        fullname: " ",
        imgpath: "img/faces/ID.jpg",
        id: " ",
        DOB: " ",
        serviceID: " ",
        birthPlace: " ",
        DOD: " ",
        occupation: " ",
        deathPlace: " ",
        deathcause: " ",
        bio: " "
    }, {
        name: "C.M. Nightingale",
        fullname: " ",
        imgpath: "img/faces/ID.jpg",
        id: " ",
        DOB: " ",
        serviceID: " ",
        birthPlace: " ",
        DOD: " ",
        occupation: " ",
        deathPlace: " ",
        deathcause: " ",
        bio: " "
    }, {
        name: "A.H. Pearce ",
        fullname: " ",
        imgpath: "img/faces/ID.jpg",
        id: " ",
        DOB: " ",
        serviceID: " ",
        birthPlace: " ",
        DOD: " ",
        occupation: " ",
        deathPlace: " ",
        deathcause: " ",
        bio: " "
    }, {
        name: "G. Potter",
        fullname: "GEOFFREY POTTER",
        imgpath: "img/faces/ID.jpg",
        id: " ",
        DOB: " ",
        serviceID: " ",
        birthPlace: " ",
        DOD: " ",
        occupation: " ",
        deathPlace: " ",
        deathcause: " ",
        bio: "Geoffrey Potter, son of Mr A. T. Potter, of Whangarei, attended the High School for part of 1913. He left early in the war with the 7th Reinforcements and was killed in France in the battle of the Somme, 1916. During the short time Geoffrey was at school he quickly gained the affection of all who came in contact with him. He was a prominent leader of the junior school and will be remembered for his kindly nature and good humour."
    }, {
        name: "H.L. Rouse",
        fullname: "Henry Lee Rouse",
        imgpath: "img/faces/ID.jpg",
        id: " ",
        DOB: " ",
        serviceID: " ",
        birthPlace: " ",
        DOD: " ",
        occupation: " ",
        deathPlace: " ",
        deathcause: " ",
        bio: "Henry Lee Rouse, son of Mr Rouse, of Hukerenui. He came to the school after the second term in 1910, leaving at the end of 1912. Entering camp in 1916 he left with the 14ths. He did not manage to reach France, but was invalided back from England and died in the Auckland Hospital in December, 1916. Rouse was a boy of splendid physique and of a very quiet, retiring disposition. During his term at school he was a member of the school fifteen and showed that he possessed the the qualities that go to make a successful forward. Being a train-boy the opportunity of knowing him well was denied us."
    }, {
        name: "N. Steadman",
        fullname: "NOEL STEADMAN",
        imgpath: "img/faces/noel_steadman.jpg",
        id: " ",
        DOB: " ",
        serviceID: " ",
        birthPlace: " ",
        DOD: " ",
        occupation: " ",
        deathPlace: " ",
        deathcause: " ",
        bio: "Noel Steadman was the son of Mr T. H. Steadman, of Whangarei, late Colonel of the 15th North Auckland Regiment. Noel was a pupil of the Whangarei High School during 1904 and 1905. In 1906 he left us to enter King’s College, Auckland. After leaving school he devoted his studies to engineering. When war broke out he enlisted and left with the Main Body as a lieutenant in the Auckland Infantry. He took part in the defence of the Suez Canal and the landing at Gallipoli and was afterwards killed on the 8th May, 1915, in the attack of Krithia."
    }, {
        name: "T.H. Storey",
        fullname: " ",
        imgpath: "img/faces/ID.jpg",
        id: " ",
        DOB: " ",
        serviceID: " ",
        birthPlace: " ",
        DOD: " ",
        occupation: " ",
        deathPlace: " ",
        deathcause: " ",
        bio: " "
    }, {
        name: "A.M. White",
        fullname: " ",
        imgpath: "img/faces/ID.jpg",
        id: " ",
        DOB: " ",
        serviceID: " ",
        birthPlace: " ",
        DOD: " ",
        occupation: " ",
        deathPlace: " ",
        deathcause: " ",
        bio: " "
    }, {
        name: "H.A. Wilkinson",
        fullname: "HAROLD WILKINSON",
        imgpath: "img/faces/ID.jpg",
        id: " ",
        DOB: " ",
        serviceID: " ",
        birthPlace: " ",
        DOD: " ",
        occupation: " ",
        deathPlace: " ",
        deathcause: " ",
        bio: "Harold Wilkinson, the only son of Mr J. Wilkinson, of Whangarei was at the High school for three years, 1907-1909, leaving to take, an appointment in Mr W. A. Carruth's office. Wilkinson had intended to take a Government appointment after sitting for Senior Civil Service, but was attracted to the law before he completed his course of study. He left with the 8th Reinforcements and was among those who lost their lives in the battle of the Somme, September, 1916. Harold was distinguished mostly by his quiet, retiring disposition. There was, however, a great deal behind his reserve and he proved his worth and manhood by enlisting at the earliest opportunity."
    }, {
        name: "F.R. Wooster",
        fullname: " ",
        imgpath: "img/faces/ID.jpg",
        id: " ",
        DOB: " ",
        serviceID: " ",
        birthPlace: " ",
        DOD: " ",
        occupation: " ",
        deathPlace: " ",
        deathcause: " ",
        bio: " "
    }


];